name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install doxygen

    - name: Generate Documentation
      run: |
        python utilities/replace_string.py -s '$TOP' -r '.' utilities/README_template.md -o README.md
        python utilities/replace_string.py -rm=True utilities/README_template.md -o documents/README_api.md
        cd documents
        doxygen Doxyfile
        cd ..
        python utilities/replace_string.py -s '$TOP' -r '../..' documents/html/index.html
        
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"
          
    - name: Create distribution 
      run: |
        mkdir distribution
        cp README.md distribution
        rm -rf source/gltf_materialx_converter/__pycache__
        cp -R source/gltf_materialx_converter distribution  
        rm -rf tests/__pycache__    
        cp -R tests distribution  

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: distribution
        path: distribution




