name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build Package 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install doxygen

    - name: Generate Documentation
      run: |
        source utilities/build_docs.sh
        
    - name: Run Unit Tests
      run: |
        source utilities/build_test.sh
          
    - name: Create Distribution 
      run: |
        mkdir distribution
        cp README.md distribution
        cp -R documents/html distribution
        rm -rf source/gltf_materialx_converter/__pycache__
        cp -R source/gltf_materialx_converter distribution
        rm -rf tests/__pycache__    
        cp -R tests distribution

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: distribution
        path: distribution




